apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - "./argocd-vs.yaml"
  - "./argocd-secret.yaml"
  - "./create-client.yaml"
configMapGenerator:
  - name: client-script
    files:
      - "./create-client.sh"
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: kustomize-generated